// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBaseDir(arg1) {
  return window['go']['main']['App']['AddBaseDir'](arg1);
}

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function GetBaseDirs() {
  return window['go']['main']['App']['GetBaseDirs']();
}

export function RemoveBaseDir(arg1) {
  return window['go']['main']['App']['RemoveBaseDir'](arg1);
}
