// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBaseDir(arg1:string):Promise<main.AddBaseDirResult>;

export function BrowseDirectory():Promise<string>;

export function GetBaseDirs():Promise<Array<string>>;

export function RemoveBaseDir(arg1:string):Promise<main.RemoveBaseDirResult>;
